name: Trigger Workflow Securely

on:
  workflow_dispatch: # Allows manual trigger or API dispatch
    inputs:
      exampleInput:
        description: 'An example input'
        required: false
        default: 'default-value'

jobs:
  trigger_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use GitHub Token from Secrets
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}  # Access token from GitHub secrets
        run: |
          echo "Triggered with input: ${{ github.event.inputs.exampleInput }}"
