name: Senior Assassin Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create_game:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use GitHub Token
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN }}
        run: |
          echo "Starting game..."
          echo "GitHub Token is: $GITHUB_TOKEN"
