name: Senior Assassin Workflow

on:
  push:
    branches:
      - main   # Trigger workflow on push to main branch
  workflow_dispatch: # Allow manual triggering via GitHub UI

jobs:
  create_game:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use GitHub Token
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN }}  # Inject GitHub secret as an environment variable
        run: |
          echo "Starting game..."
          echo "GitHub Token is: $API_TOKEN"
